### PR TITLE
Add review-summary file to LicenseCheckMojo

### PR DESCRIPTION
**Pull request by HannesWell**
With this PR I want to suggest to add a dedicated `reviewSummary` file property, which describes a separate file to that only the output of review-request-creation actions is written.
This allows to easily read the summary of created review-requests and to present it to to the requesting committer for example as a extra comment as suggested in PR #161.

### CODE REVIEW

**Comment by akurtakov** [comment]
@waynebeaton Wayne, it would be nice to have GH workflow ready as @HannesWell is working on in #161 . This change is quite simple but the bigger issue has the potential to improve things even more. I know you're working on removing the need for these but meanwhile let's not delay incremental improvements to status quo.

**Comment by waynebeaton** [comment]
Sorry for the delay, my attention has been focused elsewhere.

Shouldn't it be generating something that is more easily parsed? 

I never considered that this output would anything more than informational for the user. There's at least (from what I remember) four different things that can potentially be written out, and I'm not sure that we should be making any specific commitments regarding what it's currently generating (while I don't expect to i18n this, that's at least a possibility).

What do you actually need? e.g., wouldn't a JSON file that maps the ID to the corresponding issue be more valuable? If we get the createReviews method to return the mapping, we can pretty easily dump it.

**Comment by HannesWell** [comment]
> What do you actually need? e.g., wouldn't a JSON file that maps the ID to the corresponding issue be more valuable? If we get the createReviews method to return the mapping, we can pretty easily dump it.

The suggested change is actually sufficient for my intention. The plan is to let the workflow, which I suggested in PR #161, create a comment once reviews are created, just like I did manually in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/247#issuecomment-1116059016

So the content is not parsed. Just the most interesting part is forwarded to the user.

**Comment by waynebeaton** [comment]
My concern is mostly that by making this change, I'm committing to the implementation. As it is, the current implementation was created before we'd added proper logging to the implementation, and the nature of these messages is that they're probably a better fit as log messages. 

I think that I understand the nature of what you're asking. I'll see what I can come up with.

**Comment by waynebeaton** [comment]
I came up with a solution that I believe meets the requirements, while further decoupling the UI.

I decided to use a markdown link style in the output, e.g.,

````
[maven/mavencentral/org.apache.tika/tika-parsers/1.24.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2327)
[maven/mavencentral/xml-apis/xml-apis/1.0.b2](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2532)
[maven/mavencentral/org.apache.lucene/lucene-core/8.4.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2341)
[maven/mavencentral/javax.media/jai-core/1.1.3](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2505)
[maven/mavencentral/org.apache.cxf/cxf-core/3.3.6](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2326)
[maven/mavencentral/com.sun.media/jai-codec/1.1.3](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2506)
[maven/mavencentral/com.fasterxml.jackson.module/jackson-module-jaxb-annotations/2.13.2](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2533)
[maven/mavencentral/org.apache.tika/tika-core/1.24.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2328)

````

I lifted some bits from your solution, so I've added you as a co-author on the commit.

Does this serve the requirements?

**Comment by HannesWell** [comment]
> Does this serve the requirements?

Yes that sounds good. And is a good fit for all requirements since markdown is also displayed nicely in GH comments. Thank you!

I assume the review-file always created and just empty if no requests are created, is that correct?

**Pull request closed without merging**
