### PR TITLE
Configure explicit maven version (and use maven 3.9.2

### PR DESCRIPTION
**Pull request by laeubi**
FYI @akurtakov @HannesWell I just fear one can't really test this before it is merged or how was this done in the past?

### CODE REVIEW

**Comment by akurtakov** [comment]
I think you're correct here.

**Comment by HannesWell** [comment]
> FYI @akurtakov @HannesWell I just fear one can't really test this before it is merged or how was this done in the past?

You can Test it, for example by referencing your fork of this repo for example in your fork of the eclipse.platform.releng.aggregator repo and then trigger the corresponding Events, e.g. by extra an commit.

**Comment by laeubi** [comment]
> If at all, I think the version should be another parameter and if not set this action should be skipped.

Why not use a default that can be overridden? But given that 3.9.x is the default on Jenkins now it seems fine to use it here as well.

**Comment by HannesWell** [comment]
> > If at all, I think the version should be another parameter and if not set this action should be skipped.
> 
> Why not use a default that can be overridden? But given that 3.9.x is the default on Jenkins now it seems fine to use it here as well.

Ok. Yes, that would probably be reasonable as well.
In the end I think the most important part is that projects can override the default choosen here.

**Comment by iloveeclipse** [comment]
@waynebeaton : could you please look at this PR? Looks like this is needed to fix https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1138

**Review by HannesWell — CHANGES_REQUESTED** [review]
After a second look I noticed that all the changes should haben in the reusable/called `.github/workflows/mavenLicenseCheck.yml` instead of this composite action. Otherwise callers of the workflow cannot set a custom Maven version.
The setup-Maven Action is probably be called best before this action is called or it remains in this action and the Maven Version is propagated from the workflow (with another Input parameter).

**Comment by HannesWell** [comment]
> @waynebeaton : could you please look at this PR? Looks like this is needed to fix https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1138

I was added to the team "technology-dash-contributors" last week, but this only allows me to review changes. @waynebeaton if you want to grant me committer rights I can take care of this. The last time you asked I assumed that the workflow needs less maintanace but that seemed to be wrong.
As committer I could also take care of https://github.com/eclipse/dash-licenses/pull/241 by myself, which would simplify the general usage of the workflow in tycho-using projects and would allow to fix the check for m2e.

**Comment by HannesWell** [comment]
I have now created a follow up that implements the suggested changes from https://github.com/eclipse/dash-licenses/pull/244#pullrequestreview-1473722639.

**Comment by waynebeaton** [comment]
> @HannesWell: "if you want to grant me committer rights I can take care of this. "

I've initiated a [committer election](https://projects.eclipse.org/projects/technology.dash/elections/election-hannes-wellmann-committer-eclipse-dash).

**Comment by HannesWell** [comment]
> > @HannesWell: "if you want to grant me committer rights I can take care of this. "
> 
> I've initiated a [committer election](https://projects.eclipse.org/projects/technology.dash/elections/election-hannes-wellmann-committer-eclipse-dash).

Thank you! 😃

**Pull request closed without merging**
